server:
  error:
    include-stacktrace: never

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  datasource:
    username: ${PGUSER}
    password: ${PGPASSWORD}
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    ROOT: INFO
    web: DEBUG
