server:
  port: ${PORT:5001}

base-url: /api

springdoc:
  swagger-ui:
    path: /api-docs/

spring:
  application:
    name: task_manager

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

rollbar:
  token: 1558fdef9ae9412faeb045774de6df3b

security:
  jwt:
    secret: eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0YXNrX21hbmFnZXIiLCJpYXQiOjE2ODcxMTU3NjQsInVzZXJuYW1lIjoiZW1haWxAZW1haWwuY29tIiwiZXhwIjoxNjg3MjAyMTY0fQ.Db1I0FAfBTczvwiVgx1f25A2RJ4riWP4qlsHq4yFL9A