server:
  port: ${PORT:5001}

base-url: /api

springdoc:
  swagger-ui:
    path: /api-docs/

spring:
  application:
    name: task_manager

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

rollbar:
  token: 1558fdef9ae9412faeb045774de6df3b

rollbar_token: ${ROLLBAR_TOKEN}